bataille_navale:main.o affichage_init.o joueur.o IAniveau1.o presentation.o utilitaire.o placement.o placer_tous.o verifications.o procedure.o
	gcc -o bataille_navale main.o affichage_init.o joueur.o IAniveau1.o presentation.o utilitaire.o placement.o placer_tous.o verifications.o procedure.o

main.o:main.c
	gcc -Wall -ansi -c main.c

affichage_init.o:affichage_init.c
	gcc -Wall -ansi -c affichage_init.c

joueur.o:joueur.c
	gcc -Wall -ansi -c joueur.c

IAniveau1.o:IAniveau1.c
	gcc -Wall -ansi -c IAniveau1.c

presentation.o:presentation.c
	gcc -Wall -ansi -c presentation.c

utilitaire.o:utilitaire.c
	gcc -Wall -ansi -c utilitaire.c

placement.o:placement.c
	gcc -Wall -ansi -c placement.c

placer_tous.o:placer_tous.c
	gcc -Wall -ansi -c placer_tous.c

verifications.o:verifications.c
	gcc -Wall -ansi -c verifications.c
